#!/usr/bin/env bash

# basic usage: ./fetch-icu.sh remotes/origin/maint/maint-66
#  to check out ICU 66 maintenance branch
# advanced: ./fetch-icu.sh remotes/origin/maint/maint-66 master
#  to check out ICU 66 maintenance branch and then overlay data from master
# expected workflow: when we bump ICU we select a specific code revision,
#  then when taking data updates we bump data to a separate newer revision
#  (ideally from the maintenance branch, but if necessary, from a newer one)
# it is essential that any data changes be tested against the code revision
#  that we originally shipped. any code changes could break deployed software
#  by allowing us to produce incompatible data files

set -u
set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TOPDIR="$SCRIPTDIR/../../../"
ICU4C="$SCRIPTDIR/icu-git/icu4c/source"
DESIRED_REVISION="${1-master}"
DESIRED_DATA_REVISION="${2-}"

if [ -z $DESIRED_DATA_REVISION ]; then
echo Cloning icu-git at revision $DESIRED_REVISION;
else 
echo Cloning icu-git at revision $DESIRED_REVISION with data from $DESIRED_DATA_REVISION;
fi

set -x

pushd $SCRIPTDIR

if [ ! -d "$SCRIPTDIR/icu-git" ] ; then
    git clone https://github.com/unicode-org/icu.git icu-git
fi
cd icu-git

# create a fetch_icu branch pointing to desired revision of icu repository
git fetch origin
git clean -xffd
git checkout -B fetch_icu $DESIRED_REVISION

if [ $DESIRED_DATA_REVISION ]; then
    # a separate data revision was set, check out the data subdir from that revision
    #  and then create a temporary commit with the changes for easy introspection
    # assuming no incompatible changes have been made to the data, this updates it
    git checkout -f $DESIRED_DATA_REVISION ./icu4c/source/data
    # there is separate data used by the automated tests, overlay that as well so
    #  that we can use automated tests without false alarms about data mismatches
    git checkout -f $DESIRED_DATA_REVISION ./icu4c/source/test/testdata
    git commit -a -m "Overlay data from $DESIRED_DATA_REVISION onto $DESIRED_REVISION (auto-generated by fetch-icu.sh)"
fi

popd